package AI_assistant.state;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import Chief_event_coordinator.Classes.Booking;
import Chief_event_coordinator.Classes.Room;
import Chief_event_coordinator.Observer.BookingStatus;
import Chief_event_coordinator.State.AbstractBookingState;
import Chief_event_coordinator.State.BookingStateFactory;
import Chief_event_coordinator.State.CancelledState;
import Chief_event_coordinator.State.CheckedInState;
import Chief_event_coordinator.State.ConfirmedState;
import Chief_event_coordinator.State.ExtendedState;
import Chief_event_coordinator.State.IllegalBookingTransitionException;
import Chief_event_coordinator.State.NoShowState;
import Chief_event_coordinator.State.PendingState;

/**
 * AI-generated unit tests for the Booking State pattern.
 *
 * Source: generated by Claude (Anthropic) and then reviewed and corrected by
 * the developer. See AI_assistant/AI_TEST_REPORT.md for the prompts used, the
 * accept/modify/reject decisions, and the list of first-draft tests that failed
 * to compile or produced incorrect assertions before this corrected version.
 *
 * Every test below has been verified against the actual behaviour of the
 * production classes in Chief_event_coordinator.State.
 */
public class StateAiTest {

    private Booking newBooking() {
        return new Booking("b1", new Room(1));
    }

    // ----- PendingState -----

    @Test
    public void testNewBookingIsPending() {
        assertTrue(newBooking().getState() instanceof PendingState);
    }

    @Test
    public void testPendingConfirmDepositGoesToConfirmed() {
        Booking booking = newBooking();
        booking.confirmDeposit();
        assertTrue(booking.getState() instanceof ConfirmedState);
    }

    @Test
    public void testPendingCancelGoesToCancelled() {
        Booking booking = newBooking();
        booking.cancel();
        assertEquals(BookingStatus.CANCELLED, booking.getStatus());
    }

    // CORRECTED (was testPendingMarkNoShow, which wrongly expected NO_SHOW):
    // PENDING has no deposit yet, so a no-show is not a legal transition.
    @Test
    public void testPendingMarkNoShowIsRejected() {
        assertThrows(IllegalBookingTransitionException.class, () -> newBooking().markNoShow());
    }

    @Test
    public void testPendingExtendIsRejected() {
        assertThrows(IllegalBookingTransitionException.class, () -> newBooking().extend());
    }

    // CORRECTED expected message ("checkIn" -> "check in") to match the source.
    @Test
    public void testPendingCheckInRejectedMessage() {
        PendingState state = new PendingState();
        IllegalBookingTransitionException e = assertThrows(
                IllegalBookingTransitionException.class, () -> state.checkIn(newBooking()));
        assertEquals("Cannot check in a booking in state PENDING.", e.getMessage());
    }

    // ----- ConfirmedState -----

    @Test
    public void testConfirmedCheckInGoesToCheckedIn() {
        Booking booking = newBooking();
        booking.confirmDeposit();
        booking.checkIn();
        assertTrue(booking.getState() instanceof CheckedInState);
    }

    @Test
    public void testConfirmedMarkNoShowGoesToNoShow() {
        Booking booking = newBooking();
        booking.confirmDeposit();
        booking.markNoShow();
        assertTrue(booking.getState() instanceof NoShowState);
    }

    @Test
    public void testConfirmedCancelGoesToCancelled() {
        Booking booking = newBooking();
        booking.confirmDeposit();
        booking.cancel();
        assertEquals(BookingStatus.CANCELLED, booking.getStatus());
    }

    @Test
    public void testConfirmedCannotConfirmAgain() {
        ConfirmedState state = new ConfirmedState();
        assertThrows(IllegalBookingTransitionException.class,
                () -> state.confirmDeposit(newBooking()));
    }

    // ----- CheckedInState -----

    @Test
    public void testCheckedInExtendGoesToExtended() {
        Booking booking = newBooking();
        booking.confirmDeposit();
        booking.checkIn();
        booking.extend();
        assertTrue(booking.getState() instanceof ExtendedState);
    }

    // CORRECTED (was testCheckedInCanCancel, which wrongly expected success):
    // a checked-in booking can no longer be cancelled (Req8).
    @Test
    public void testCheckedInCancelIsRejected() {
        CheckedInState state = new CheckedInState();
        assertThrows(IllegalBookingTransitionException.class, () -> state.cancel(newBooking()));
    }

    @Test
    public void testCheckedInStatus() {
        assertEquals(BookingStatus.CHECKED_IN, new CheckedInState().getStatus());
    }

    // ----- ExtendedState -----

    // CORRECTED (was testExtendedCannotExtendAgain, which wrongly expected a
    // rejection): EXTENDED bookings can be extended again, staying EXTENDED.
    @Test
    public void testExtendedCanExtendAgain() {
        Booking booking = newBooking();
        booking.confirmDeposit();
        booking.checkIn();
        booking.extend();
        booking.extend();
        assertEquals(BookingStatus.EXTENDED, booking.getStatus());
    }

    @Test
    public void testExtendedCannotBeCancelled() {
        ExtendedState state = new ExtendedState();
        assertThrows(IllegalBookingTransitionException.class, () -> state.cancel(newBooking()));
    }

    // ----- CancelledState (terminal) -----

    @Test
    public void testCancelledStatus() {
        assertEquals(BookingStatus.CANCELLED, new CancelledState().getStatus());
    }

    @Test
    public void testCancelledConfirmDepositIsRejected() {
        assertThrows(IllegalBookingTransitionException.class,
                () -> new CancelledState().confirmDeposit(null));
    }

    @Test
    public void testCancelledExtendIsRejected() {
        assertThrows(IllegalBookingTransitionException.class,
                () -> new CancelledState().extend(null));
    }

    // ----- NoShowState (terminal) -----

    @Test
    public void testNoShowStatus() {
        assertEquals(BookingStatus.NO_SHOW, new NoShowState().getStatus());
    }

    @Test
    public void testNoShowCheckInIsRejected() {
        assertThrows(IllegalBookingTransitionException.class,
                () -> new NoShowState().checkIn(null));
    }

    // ----- AbstractBookingState default behaviour -----

    @Test
    public void testAbstractDefaultRejectsWithStatusInMessage() {
        AbstractBookingState anyState = new AbstractBookingState() {
            @Override
            public BookingStatus getStatus() {
                return BookingStatus.ACTIVE;
            }
        };
        IllegalBookingTransitionException e = assertThrows(
                IllegalBookingTransitionException.class, () -> anyState.cancel(null));
        assertEquals("Cannot cancel a booking in state ACTIVE.", e.getMessage());
    }

    // ----- BookingStateFactory -----

    @Test
    public void testFactoryPending() {
        assertTrue(BookingStateFactory.fromStatus(BookingStatus.PENDING) instanceof PendingState);
    }

    @Test
    public void testFactoryActiveIsPending() {
        assertTrue(BookingStateFactory.fromStatus(BookingStatus.ACTIVE) instanceof PendingState);
    }

    @Test
    public void testFactoryConfirmed() {
        assertTrue(BookingStateFactory.fromStatus(BookingStatus.CONFIRMED) instanceof ConfirmedState);
    }

    @Test
    public void testFactoryCheckedIn() {
        assertTrue(BookingStateFactory.fromStatus(BookingStatus.CHECKED_IN) instanceof CheckedInState);
    }

    @Test
    public void testFactoryExtended() {
        assertTrue(BookingStateFactory.fromStatus(BookingStatus.EXTENDED) instanceof ExtendedState);
    }

    @Test
    public void testFactoryCancelled() {
        assertTrue(BookingStateFactory.fromStatus(BookingStatus.CANCELLED) instanceof CancelledState);
    }

    @Test
    public void testFactoryNoShow() {
        assertTrue(BookingStateFactory.fromStatus(BookingStatus.NO_SHOW) instanceof NoShowState);
    }

    // ----- IllegalBookingTransitionException -----

    @Test
    public void testExceptionMessage() {
        assertEquals("oops", new IllegalBookingTransitionException("oops").getMessage());
    }

    @Test
    public void testExceptionIsRuntime() {
        assertTrue(new IllegalBookingTransitionException("x") instanceof RuntimeException);
    }
}
